---
timezone:
  jstpath: "/usr/share/zoneinfo/Asia/Tokyo"
timesync:
  servers:
    - 169.254.169.123
postfix:
  mainconf: "/etc/postfix/main.cf"
  masterconf: "/etc/postfix/master.cf"
  inet_protocols: "ipv4"
  relayhost: "xxx.xxx.xxx.xxx"
  sasl_passwd: "/etc/postfix/sasl_passwd"
  ses_settings:
    relayhost: email-smtp.us-west-2.amazonaws.com
    smtp_sasl_auth_enable: "yes"
    smtp_sasl_security_options: "noanonymous"
    smtp_sasl_password_maps: "hash:/etc/postfix/sasl_passwd"
    smtp_use_tls: "yes"
    smtp_tls_security_level: "encrypt"
    smtp_tls_note_starttls_offer: "yes"
    smtp_tls_CAfile: "/etc/ssl/certs/ca-bundle.crt"
zabbix:
  repository: "https://repo.zabbix.com/zabbix/4.0/rhel/7/x86_64/zabbix-release-4.0-1.el7.noarch.rpm"
  server: "x.x.x.x"
  conf: "/etc/zabbix/zabbix_agentd.conf"
  include_dir: "/etc/zabbix/zabbix_agentd.d"
  conf_items:
    - name: "HostMetadata"
      value: "Linux"
sudo:
  conf: "/etc/sudoers"
  sudo_users:
    - hoge
  sudo_mailto: "hoge@domain.co.jp"
ssh:
  conf: "/etc/ssh/sshd_config"
  conf_items:
    AddressFamily: "inet"
    ListenAddress: "0.0.0.0"
    PasswordAuthentication: "yes"
    Subsystem: "sftp /usr/libexec/openssh/sftp-server -l VERBOSE"
    PermitRootLogin: "no"
cloud:
  conf: "/etc/cloud/cloud.cfg"
  conf_items:
    ssh_pwauth: "true"
syslog:
  conf: "/etc/rsyslog.conf"
  servers:
    - ip: "x.x.x.x"
      port: "10530"
    - ip: "x.x.x.x"
      port: "10530"
kernel:
  sysctl_conf: "/etc/sysctl.conf"
  params:
    disable_ipv6:
      net.ipv6.conf.all.disable_ipv6: "1"
      net.ipv6.conf.default.disable_ipv6: "1"
service:
  disable:
    - atd
    - auditd
    - dbus
    - rpcbind
    - rngd
      
    